### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by andreypopov** [subzero79/node-red-contrib-tuya-local#1]
no connect,
also, please add examples

**Comment by andreypopov** [comment]
"TypeError: device.find is not a function"

**Comment by andreypopov** [comment]
{
	"result": [{
		"result": [{
			"uid": "eu1565264867466vdqbK",
			"password": "6e74afddf34d2554",
			"code": "mebf95c28ded87f62d05ra",
			"pv": "2.1",
			"meshKey": "D159492ED22539FC1DF118D0BCE31B57",
			"name": "29CF18C6C6155B074EA886D54CD2C25B",
			"share": false,
			"ownerId": "5358136",
			"meshId": "mebf95c28ded87f62d05ra",
			"localKey": "0b16e8d5a422c87b"
		}],
		"a": "tuya.m.device.sig.mesh.list",
		"t": 1565429752496,
		"success": true,
		"v": "1.0",
		"status": "ok"
	}, {
		"result": [{
			"protocolVer": "2.1",
			"code": "tymesh1565265458",
			"pv": "2.1",
			"ownerId": "5358136",
			"type": 0,
			"meshId": "mebf0637f24940f2568abj",
			"uid": "eu1565264867466vdqbK",
			"password": "fd15553ffa5c6716",
			"name": "tymesh1565265458",
			"share": false,
			"id": "mebf0637f24940f2568abj",
			"localKey": "4775d204767d838c"
		}],
		"a": "tuya.m.my.group.mesh.list",
		"t": 1565429752494,
		"success": true,
		"v": "1.0",
		"status": "ok"
	}, {
		"result": {
			"geoName": "",
			"rooms": [],
			"gid": 5358136,
			"groupId": 5358136,
			"displayOrder": 0,
			"admin": true,
			"lon": 0.0,
			"dealStatus": 2,
			"groupUserId": 5561049,
			"background": "",
			"name": "Мой дом ..",
			"id": 4241547,
			"lat": 0.0
		},
		"a": "tuya.m.location.get",
		"t": 1565429752500,
		"success": true,
		"v": "2.0",
		"status": "ok"
	}, {
		"result": [],
		"a": "tuya.m.my.group.device.group.list",
		"t": 1565429752494,
		"success": true,
		"v": "2.0",
		"status": "ok"
	}, {
		"result": [{
			"virtual": false,
			"lon": "27.64197797514828",
			"uuid": "478803312cf43203f93d",
			"iconUrl": "https://images.tuyaeu.com/smart/icon/15318984469lklgyxkr6b_0.png",
			"lat": "53.93942845143881",
			"runtimeEnv": "prod",
			"devId": "478803312cf43203f93d",
			"dpMaxTime": 1565429679539,
			"productId": "8QMq5QyBkZDiA8ME",
			"dps": {
				"22": 600,
				"23": 29171,
				"1": false,
				"24": 16586,
				"25": 1255,
				"26": 0,
				"17": 0,
				"18": 0,
				"19": 0,
				"9": 0,
				"20": 2332,
				"21": 1
			},
			"activeTime": 1565429589,
			"ip": "178.172.193.216",
			"moduleMap": {
				"wifi": {
					"upgradeStatus": 0,
					"bv": "5.42",
					"cdv": "1.0.0",
					"pv": "2.2",
					"verSw": "1.1.1",
					"isOnline": true,
					"id": 11135590,
					"cadv": ""
				},
				"mcu": {
					"upgradeStatus": 0,
					"cdv": "",
					"verSw": "1.1.1",
					"isOnline": true,
					"id": 11135591,
					"cadv": ""
				}
			},
			"devAttribute": 3,
			"name": "Smart Plug 2",
			"timezoneId": "Europe/Minsk",
			"category": "cz",
			"localKey": "34ead6cf78856eda"
		}],
		"a": "tuya.m.my.group.device.list",
		"t": 1565429752506,
		"success": true,
		"v": "1.0",
		"status": "ok"
	}, {
		"result": [{
			"schemaInfo": {
				"schema": "[{\"mode\":\"rw\",\"code\":\"switch_1\",\"name\":\"开关1\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power\",\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"countdown_1\",\"name\":\"开关1倒计时\",\"property\":{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_time2\",\"id\":9,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"add_ele\",\"name\":\"增加电量\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100,\"type\":\"value\"},\"iconname\":\"icon-battery\",\"id\":17,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"cur_current\",\"name\":\"当前电流\",\"property\":{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-Ele\",\"id\":18,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"cur_power\",\"name\":\"当前功率\",\"property\":{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_tool\",\"id\":19,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"cur_voltage\",\"name\":\"当前电压\",\"property\":{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-a_function_turbo\",\"id\":20,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"test_bit\",\"name\":\"产测结果位\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":5,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-dp_direction\",\"id\":21,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"voltage_coe\",\"name\":\"电压校准系数\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-gaodiyin\",\"id\":22,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"electric_coe\",\"name\":\"电流校准系数\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-gaodiyin\",\"id\":23,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"power_coe\",\"name\":\"功率校准系数\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-gaodiyin\",\"id\":24,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"electricity_coe\",\"name\":\"电量校准系数\",\"property\":{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1,\"type\":\"value\"},\"iconname\":\"icon-gaodiyin\",\"id\":25,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"ro\",\"code\":\"fault\",\"scope\":\"fault\",\"name\":\"故障告警\",\"property\":{\"label\":[\"ov_cr\"],\"type\":\"bitmap\",\"maxlen\":1},\"id\":26,\"type\":\"obj\",\"desc\":\"ov_cr：过流保护\"}]",
				"schemaExt": "[{\"id\":1,\"inputStyle\":\"\",\"inputType\":\" \"},{\"id\":9,\"inputStyle\":\"\",\"inputType\":\" \"},{\"id\":17,\"inputStyle\":\"\",\"inputType\":\" \"}]"
			},
			"capability": 1,
			"uiInfo": {
				"phase": "release",
				"appRnVersion": "5.1",
				"rnFind": true,
				"ui": "00000002en_1.1.14",
				"id": 757339,
				"type": "RN"
			},
			"panelConfig": {
				"bic": [{
					"code": "timer",
					"selected": true
				}, {
					"code": "jump_url",
					"selected": false
				}],
				"fun": {
					"showBatteryStats": true
				}
			},
			"shortcut": {
				"quickOpDps": [],
				"faultDps": [],
				"displayDps": [],
				"switchDp": 1,
				"displayMsgs": {}
			},
			"i18nTime": 1558096125145,
			"id": "8QMq5QyBkZDiA8ME",
			"attribute": 1969028,
			"category": "cz",
			"supportGroup": true,
			"meshCategory": ""
		}],
		"a": "tuya.m.device.ref.info.my.list",
		"t": 1565429752528,
		"success": true,
		"v": "4.0",
		"status": "ok"
	}, {
		"result": {},
		"a": "tuya.m.my.group.device.relation.list",
		"t": 1565429752494,
		"success": true,
		"v": "2.0",
		"status": "ok"
	}, {
		"result": [{
			"bizType": 6,
			"bizId": "478803312cf43203f93d",
			"displayOrder": -1,
			"roomId": "-1",
			"homeDisplayOrder": 0
		}],
		"a": "tuya.m.my.group.device.sort.list",
		"t": 1565429752500,
		"success": true,
		"v": "1.0",
		"status": "ok"
	}, {
		"result": [],
		"a": "tuya.m.my.shared.device.group.list",
		"t": 1565429752494,
		"success": true,
		"v": "2.0",
		"status": "ok"
	}, {
		"result": [],
		"a": "tuya.m.my.shared.device.list",
		"t": 1565429752494,
		"success": true,
		"v": "1.0",
		"status": "ok"
	}],
	"t": 1565429752528,
	"success": true,
	"status": "ok"
}

**Comment by andreypopov** [comment]
![2019-08-10_12-42-45](https://user-images.githubusercontent.com/1624839/62820392-6d87f700-bb6c-11e9-83f8-2fc2a808bb0f.png)

**Comment by subzero79** [comment]
I think is missing the tuyapi library. I’ll add later on tonite examples how to install.

**Comment by subzero79** [comment]
@andreypopov i added more info to the readme. Can you please tell me how are you running nodered?

**Comment by andreypopov** [comment]
Wow, it works now:) great work

**Comment by andreypopov** [comment]
![2019-08-11_09-12-51](https://user-images.githubusercontent.com/1624839/62830484-9239a880-bc18-11e9-9159-170d649438f1.png)

why it is in "connecting" state

**Comment by subzero79** [comment]
I don’t know. Did you get a green connected icon ?

**Comment by andreypopov** [comment]
![2019-08-11_17-09-16](https://user-images.githubusercontent.com/1624839/62834880-c46bfa00-bc5a-11e9-9c48-928ad400e3d8.png)
yeah
