### ISSUE TITLE
Only updates when app is open

### ISSUE THREAD

**Issue by moryoav** [subzero79/node-red-contrib-tuya-local#16]
I installed this on my node-red (running on Windows 10, latest build, I don't think it matters).
I have a smart plug that reports its power consumption. That's the data I want to retrieve.
The problem: I can send "Request" and data is returned from the node, but not the correct data. Data is only updated correctly if I have the Smart Life app open on my phone and I go to "Electric" tab to see the data from the device on the app. I'll then see the same data on the app and coming out of this node. If I terminate the app on the phone, data stops being correct. "Request" just retrieves the last thing it saw before the app was terminated. 
Anything I should try doing? Thank you.

Edit: Seems to be a problem related directly to Tuyapi and not to this node.

**Comment by slombard3000** [comment]
Works OK with my strip lights... the DSP index for on and off is 20 not 1.
