### ISSUE TITLE
Payload unreadable

### ISSUE THREAD

**Issue by E-NINA** [subzero79/node-red-contrib-tuya-local#19]
Hello,

I installed this node and I was able to connect to my device.
It is a window blind roller switch:

https://www.aliexpress.com/item/4000051743871.html?spm=a2g0s.9042311.0.0.2742b90ac0c8fL

I know probably this isn't covered by tuyapi but as I get a connection and replay back from the unit might be something I'm doing wrong.
Issue is that payload info I get is unreadble, see piucture below:

![Capture](https://user-images.githubusercontent.com/42787097/72224987-1d2c1f80-3578-11ea-90c8-aaac84e4eb9e.PNG)

Ony hint possible?

Thanks

**Comment by subzero79** [comment]
Could be that the protocol is wrong. Try setting to 3.1

**Comment by E-NINA** [comment]
I try your suggestion, with no luck.
with 3.1 connects, but with request command no replay
with 3.2 keeps on a loop connected them disconnected
with 3.3 connects and get replay from "request" command

I don't know if this helps but on tuya app for firmware info displays Wi-Fi / MCU Module: 1.0.6

**Comment by subzero79** [comment]
I think that’s the same fw I have in my last and only switch.  Looks like a decryption gone wrong. Have you double checked the key and id is correct?

**Comment by E-NINA** [comment]
Key and id I checked and seems are OK.

**Comment by subzero79** [comment]
Don't have any more answers. I'd recommend you install tuyapi in a nodejs env. Then create js script file as documented in tuyapi to test the connection. If you see the same output then something is wrong at decoding in tuyapi.

**Comment by E-NINA** [comment]
Hello again,
Today I've just double checked again and I was using by mistake ""productId" as the "localKey".
I corrected that but issues are the same, get on node-red also connection but same unreadable payload.
One information to add is that if I try change/add any information to "Rename schema", Node-red crashes, see logs below:

"
13 Jan 22:53:14 - [info] [tuya-local:6d1d64d8.3e4efc] No timeout defined for socket1, probably NodeRED starting
13 Jan 22:53:14 - [red] Uncaught Exception:
13 Jan 22:53:14 - TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keyRename (/data/node_modules/node-red-contrib-tuya-local/lib/utils.js:8:27)
    at TuyaDevice.TuyaNode.device.on (/data/node_modules/node-red-contrib-tuya-local/tuya-local.js:110:53)
    at TuyaDevice.emit (events.js:198:13)
    at TuyaDevice._packetHandler (/data/node_modules/tuyapi/index.js:411:10)
    at packets.forEach.packet (/data/node_modules/tuyapi/index.js:315:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (/data/node_modules/tuyapi/index.js:311:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/node-red/.npm/_logs/2020-01-13T22_53_14_843Z-debug.log
"

**Comment by subzero79** [comment]
Please use the tuyapi script to test this. It looks to me that the keys are wrong. Is this your first tuya device? Please go again using a mitm proxy to check they are correct.

**Comment by E-NINA** [comment]
Yes is my first tuya device, I managed to setup MITM proxy and you are right key was wrong.
Now I get a right mensagem on paylod. The only point just for future reference is that on node-red displays as connected, with wrong key
Sorry for this issue.
