### ISSUE TITLE
Node not listed

### ISSUE THREAD

**Issue by Shamshala** [subzero79/node-red-contrib-tuya-local#20]
Hi, first of all i'm really new to Node-Red so please don't kill me :D . Did I do something wrong or was this supposed to happen?
![nodered](https://user-images.githubusercontent.com/28995424/73127612-4363ad80-3fc3-11ea-8a64-68842d76d036.png)

It seems like something has been installed but tuya node isn't listed.

I would be happy for any help. Thanks!

**Comment by subzero79** [comment]
I think you need to restart the docker container.

**Comment by Shamshala** [comment]
Wow, that was quick! If you've meant after the attempt to install it i've done it after the screen was made and it doesn't work.

Forgot to mention, it's Ubuntu 18.04.3 (if it matters) and NodeRED v1.0.3.


EDIT: So these Warnings are perfectly ok, right?

**Comment by subzero79** [comment]
Ok. Could be the nodered container is not the official is hassio addon so I don’t know where persistent folder is(/data).  Could be the same could be not. Check that, and install from that folder. Also maybe hassio has other ways of installing external packages. 
Let me know

**Comment by Shamshala** [comment]
It is installed via official hassio "Add-on store".     EDIT: (oh sorry, i missed your point)

Should it be installed in the folder where other node modules are installed (folder "/opt/node_modules")? Or it should be really in /data? (it creates new folder "node_modules" and some other files - not listed now because i reinstalled the container)
![rergewheherswhgreherherw](https://user-images.githubusercontent.com/28995424/73127776-11a01600-3fc6-11ea-9769-ef8fb19ac6ee.png)

**Comment by Shamshala** [comment]
Oooooh, i get it now. So for external packages i need to specificaly input the npm path to configuration of the addon what i want to install. Odd :smile: 

Thank you @subzero79 !
