### ISSUE TITLE
Node is returning message with bad formatting

### ISSUE THREAD

**Issue by fmgyotoku** [subzero79/node-red-contrib-tuya-local#31]
Howdy!
I used this node some time ago with great results and I'm trying now a new node-red implementation on a raspberry pi. So I installed **tuyapi**, **tuya-cli** and the **node-red-contrib-tuya-local**. 

When I ran the tuya-cli, I can get all the device IDs and local keys as expected.

Also, when I configured the node and deployed the flow, I could see that the connection was returning connected status as per the screenshot. 
![image](https://user-images.githubusercontent.com/16383458/93031057-43f0a780-f66b-11ea-9b46-1b1a1fdb46e5.png)

However, the debug is returning an awkward message from the node:
![image](https://user-images.githubusercontent.com/16383458/93031070-5ec31c00-f66b-11ea-8eb3-12684e593cea.png)

When I listed the npm installation, I found the following details for the node package:
![image](https://user-images.githubusercontent.com/16383458/93031169-16f0c480-f66c-11ea-8cc0-6dba2ca95471.png)

Could this be any dependency compatibility issue? Is it possible to point to the 3.2.3 tuya library instead of the 5.1.2? How could this be achieved?

**Comment by subzero79** [comment]
That looks to me like incorrect decryption. I would check the keys and deviceid are correct.

**Comment by fmgyotoku** [comment]
@subzero79 , you are right. I tested with another smart plug and it worked well. I guess there might be something with the device I was using before. I will close this issue. Thanks a lot for the quick response! 👍
